class SherryPath:

    @classmethod
    def path_exists(cls, path: str) -> bool: ...

    @classmethod
    def path_create(cls, path: str) -> str: ...

    @classmethod
    def link(cls, source: str, target: str, create: bool = False) -> str: ...

    @property
    def package_path(self) -> str: ...

    @property
    def package_resource_path(self) -> str: ...

    @property
    def package_qss_path(self) -> str: ...

    @property
    def package_img_path(self) -> str: ...

    @property
    def project_path(self) -> str: ...

    @property
    def project_resource_path(self) -> str: ...

    @property
    def project_img_path(self) -> str: ...

    @property
    def project_qss_path(self) -> str: ...

    @property
    def log_path(self) -> str: ...

    @property
    def user_home(self) -> str: ...

    @property
    def user_desktop(self) -> str: ...

    def file_path(self, file_name: str) -> str: ...
