# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bar(object):
    def setupUi(self, bar):
        bar.setObjectName("bar")
        bar.resize(636, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_bar_app_logo = QtWidgets.QPushButton(bar)
        self.btn_bar_app_logo.setText("")
        self.btn_bar_app_logo.setObjectName("btn_bar_app_logo")
        self.horizontalLayout.addWidget(self.btn_bar_app_logo)
        self.btn_bar_app_name = QtWidgets.QPushButton(bar)
        self.btn_bar_app_name.setText("")
        self.btn_bar_app_name.setObjectName("btn_bar_app_name")
        self.horizontalLayout.addWidget(self.btn_bar_app_name)
        spacerItem = QtWidgets.QSpacerItem(425, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_bar_min = QtWidgets.QPushButton(bar)
        self.btn_bar_min.setText("")
        self.btn_bar_min.setObjectName("btn_bar_min")
        self.horizontalLayout.addWidget(self.btn_bar_min)
        self.btn_bar_normal = QtWidgets.QPushButton(bar)
        self.btn_bar_normal.setText("")
        self.btn_bar_normal.setObjectName("btn_bar_normal")
        self.horizontalLayout.addWidget(self.btn_bar_normal)
        self.btn_bar_close = QtWidgets.QPushButton(bar)
        self.btn_bar_close.setText("")
        self.btn_bar_close.setObjectName("btn_bar_close")
        self.horizontalLayout.addWidget(self.btn_bar_close)

        self.retranslateUi(bar)
        QtCore.QMetaObject.connectSlotsByName(bar)

    def retranslateUi(self, bar):
        _translate = QtCore.QCoreApplication.translate
        bar.setWindowTitle(_translate("bar", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bar = QtWidgets.QWidget()
    ui = Ui_bar()
    ui.setupUi(bar)
    bar.show()
    sys.exit(app.exec_())
