# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_example_welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_index_body(object):
    def setupUi(self, index_body):
        index_body.setObjectName("index_body")
        index_body.resize(1029, 791)
        index_body.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(index_body)
        self.horizontalLayout.setContentsMargins(30, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.index_show_image = QtWidgets.QWidget(index_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.index_show_image.sizePolicy().hasHeightForWidth())
        self.index_show_image.setSizePolicy(sizePolicy)
        self.index_show_image.setMinimumSize(QtCore.QSize(410, 583))
        self.index_show_image.setObjectName("index_show_image")
        self.horizontalLayout.addWidget(self.index_show_image)
        self.index_text_body = QtWidgets.QWidget(index_body)
        self.index_text_body.setObjectName("index_text_body")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.index_text_body)
        self.verticalLayout.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 195, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.index_text_show = QtWidgets.QTextBrowser(self.index_text_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.index_text_show.sizePolicy().hasHeightForWidth())
        self.index_text_show.setSizePolicy(sizePolicy)
        self.index_text_show.setMinimumSize(QtCore.QSize(500, 300))
        self.index_text_show.setObjectName("index_text_show")
        self.verticalLayout.addWidget(self.index_text_show)
        spacerItem1 = QtWidgets.QSpacerItem(20, 195, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.index_btn_body = QtWidgets.QWidget(self.index_text_body)
        self.index_btn_body.setObjectName("index_btn_body")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.index_btn_body)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.index_close_btn = QtWidgets.QPushButton(self.index_btn_body)
        self.index_close_btn.setObjectName("index_close_btn")
        self.horizontalLayout_2.addWidget(self.index_close_btn)
        self.verticalLayout.addWidget(self.index_btn_body)
        self.index_text_show.raise_()
        self.index_show_image.raise_()
        self.index_btn_body.raise_()
        self.horizontalLayout.addWidget(self.index_text_body)
        spacerItem3 = QtWidgets.QSpacerItem(36, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)

        self.retranslateUi(index_body)
        QtCore.QMetaObject.connectSlotsByName(index_body)

    def retranslateUi(self, index_body):
        _translate = QtCore.QCoreApplication.translate
        index_body.setWindowTitle(_translate("index_body", "Form"))
        self.index_text_show.setHtml(_translate("index_body", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">您已经成功安装EQ，请您直接起飞，谢谢。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">You have successfully installed the EQ, please take off directly with your work , thank you.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">访问 Document: <span style=\" text-decoration: underline; color:#0055ff;\">https://py-mu.github.io/easy-pyqt/</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">访问 Github:   <span style=\" text-decoration: underline; color:#0055ff;\">https://github.com/py-mu/easy-pyqt</span></p></body></html>"))
        self.index_close_btn.setToolTip(_translate("index_body", "<html><head/><body><p><span style=\" font-size:10pt;\">关闭欢迎页</span></p><p>Close Welcome Activity</p></body></html>"))
        self.index_close_btn.setText(_translate("index_body", "关闭"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    index_body = QtWidgets.QWidget()
    ui = Ui_index_body()
    ui.setupUi(index_body)
    index_body.show()
    sys.exit(app.exec_())
